name: .NET CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release
        
      # - name: Run application
      #   run: dotnet run --project HelloWorld/HelloWorld.csproj

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_ID }}/dotnet-hello:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_ID }}/dotnet-hello:latest
              
      # - name: Start Minikube
      #   run: |
      #     minikube profile list 
      #     minikube start --driver=docker --kubernetes-version=v1.34.0 --profile=minikube

      - name: Port Forward to localhost
        run: |
          minikube tunnel
      # 7️⃣ Ensure kubectl points to minikube
      - name: Configure kubectl
        run: |
          minikube kubectl -- config use-context minikube
          kubectl get nodes
  
      # 8️⃣ Apply Kubernetes manifests (skip OpenAPI validation)
      - name: Deploy to Kubernetes
        run: |
          kubectl apply --validate=false -f k8s/deployment.yaml
          kubectl apply --validate=false -f k8s/service.yaml
      # - name: Port Forward to localhost
      #   run: |
            # minikube tunnel
            # kubectl port-forward service/helloworld-service 8080:80
  
      # 9️⃣ Show pod status
      - name: Verify Deployment
        run: kubectl get pods -o wide
