name: .NET CI + Push to ECR

on:
  push:
    branches: ["main"]

jobs:
  build-push-ecr:
    runs-on: ubuntu-latest

    steps:

      # 1Ô∏è‚É£ Checkout Code
      - name: Checkout
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # 3Ô∏è‚É£ Build & Test
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal

      # 4Ô∏è‚É£ Configure AWS Credentials (Official)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 5Ô∏è‚É£ Login to AWS ECR (Official)
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 6Ô∏è‚É£ Build & Push Docker Image to ECR
      - name: Build, Tag & Push Docker Image
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/mk-ecr-dotnet:latest
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "üìå Image pushed to: $IMAGE"
